-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWaKks/K0GLMdkLMF
YLTMi+ytQUFceSjDzfwEOwki43+gCgYIKoZIzj0DAQehRANCAAQwSLYsRJXc8LKY
GAlGClPCH+XByT1iqbUEXvzECrBfhpm7WvbLyV6fW7oIiBlaOdyms9Q8hbbcsHkm
XMMrW8Es
-----END PRIVATE KEY-----