package com.algomeet.authservice.util;

import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.regex.Pattern;

import org.springframework.util.StringUtils;

public class SecurityQuestionSha256Util {
	// Regex to check if a string is a 64-character hexadecimal string
	private static final Pattern SHA256_HEX_PATTERN = Pattern.compile("^[0-9a-fA-F]{64}$");

	/**
	 * Checks if a string is a valid SHA-256 hexadecimal representation.
	 * This only validates the format and length, not if it was actually generated by SHA-256.
	 *
	 * @param hashString The string to check.
	 * @return true if the string is a 64-character hexadecimal string, false otherwise.
	 */
	public static boolean isValidSha256Format(String hashString) {
		if (!StringUtils.hasLength(hashString)) {
			return false;
		}
		
		return SHA256_HEX_PATTERN.matcher(hashString).matches();
	}

	public static String hashAnswer(String answer) throws NoSuchAlgorithmException, UnsupportedEncodingException {
		if (!StringUtils.hasLength(answer)) {
			throw new RuntimeException("Invalid input answer has not value");
		}

		return generateSha256Hash(answer.trim().toLowerCase());	 
	}
	
	public static boolean verifyAnswer(String answer, String expectedAnswer) throws NoSuchAlgorithmException, UnsupportedEncodingException {
		if (!StringUtils.hasLength(answer)) {
			throw new RuntimeException("Invalid input answer has not value");
		}

		return verifySha256Hash(answer.trim().toLowerCase(), expectedAnswer);	 
	}

	/**
	 * Generates the SHA-256 hash of a given input string.
	 *
	 * @param input The string to hash.
	 * @return The SHA-256 hash as a hexadecimal string, or null if an error occurs.
	 */
	public static String generateSha256Hash(String input) {
		try {
			MessageDigest digest = MessageDigest.getInstance("SHA-256");
			byte[] hashBytes = digest.digest(input.getBytes("UTF-8"));
			StringBuilder hexString = new StringBuilder();
			for (byte b : hashBytes) {
				String hex = Integer.toHexString(0xff & b);
				if (hex.length() == 1) {
					hexString.append('0');
				}
				hexString.append(hex);
			}
			return hexString.toString();
		} catch (NoSuchAlgorithmException | java.io.UnsupportedEncodingException e) {
			e.printStackTrace();
			return null;
		}
	}

	/**
	 * Verifies if a given hash string matches the SHA-256 hash of a given input.
	 *
	 * @param input The original input string.
	 * @param expectedHash The hash string to verify against.
	 * @return true if the generated hash of the input matches the expected hash, false otherwise.
	 */
	public static boolean verifySha256Hash(String input, String expectedHash) {
		String generatedHash = generateSha256Hash(input);
		return generatedHash != null && generatedHash.equalsIgnoreCase(expectedHash);
	}
}
