spring:
  config:
    activate:
      on-profile: prod
  application:
    name: xmpp-chat-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI_AUTHDB}
      auto-index-creation: true

    redis:
      host: redis-svc
      port: 6379
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8097

xmpp:
  server:
    port: 8098
    domain: algomeet.com
    group-chat-domain: conference.algomeet.com

jwt:
  secret: ${SPRING_JWT_SECRET}

feign:
  client:
    group-service:
      url: http://group-service:8087
    media-service:
      url: http://media-service:8095
