spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:

    url: jdbc:postgresql://localhost:5432/clorameet_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



  redis:
    host: localhost
    port: 6379

  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8082
