/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_algomeet_signalingservice_jni_Opaque */

#ifndef _Included_com_algomeet_signalingservice_jni_Opaque
#define _Included_com_algomeet_signalingservice_jni_Opaque
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_register
 * Signature: (Ljava/lang/String;[BLcom/algomeet/signalingservice/jni/OpaqueIds;)Lcom/algomeet/signalingservice/jni/OpaqueRecExpKey;
 */
JNIEXPORT jobject JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1register__Ljava_lang_String_2_3BLcom_algomeet_signalingservice_jni_OpaqueIds_2
  (JNIEnv *, jclass, jstring, jbyteArray, jobject);

/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_register
 * Signature: (Ljava/lang/String;Lcom/algomeet/signalingservice/jni/OpaqueIds;)Lcom/algomeet/signalingservice/jni/OpaqueRecExpKey;
 */
JNIEXPORT jobject JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1register__Ljava_lang_String_2Lcom_algomeet_signalingservice_jni_OpaqueIds_2
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_register
 * Signature: (Ljava/lang/String;[B)Lcom/algomeet/signalingservice/jni/OpaqueRecExpKey;
 */
JNIEXPORT jobject JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1register__Ljava_lang_String_2_3B
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_register
 * Signature: (Ljava/lang/String;)Lcom/algomeet/signalingservice/jni/OpaqueRecExpKey;
 */
JNIEXPORT jobject JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1register__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_createCredReq
 * Signature: (Ljava/lang/String;)Lcom/algomeet/signalingservice/jni/OpaqueCredReq;
 */
JNIEXPORT jobject JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1createCredReq
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_createCredResp
 * Signature: ([B[BLcom/algomeet/signalingservice/jni/OpaqueIds;Ljava/lang/String;)Lcom/algomeet/signalingservice/jni/OpaqueCredResp;
 */
JNIEXPORT jobject JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1createCredResp
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jstring);

/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_recoverCreds
 * Signature: ([B[BLjava/lang/String;Lcom/algomeet/signalingservice/jni/OpaqueIds;)Lcom/algomeet/signalingservice/jni/OpaqueCreds;
 */
JNIEXPORT jobject JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1recoverCreds
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jstring, jobject);

/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_userAuth
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1userAuth
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_createRegReq
 * Signature: (Ljava/lang/String;)Lcom/algomeet/signalingservice/jni/OpaqueRegReq;
 */
JNIEXPORT jobject JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1createRegReq
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_createRegResp
 * Signature: ([B[B)Lcom/algomeet/signalingservice/jni/OpaqueRegResp;
 */
JNIEXPORT jobject JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1createRegResp___3B_3B
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_createRegResp
 * Signature: ([B)Lcom/algomeet/signalingservice/jni/OpaqueRegResp;
 */
JNIEXPORT jobject JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1createRegResp___3B
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_finalizeReg
 * Signature: ([B[BLcom/algomeet/signalingservice/jni/OpaqueIds;)Lcom/algomeet/signalingservice/jni/OpaquePreRecExpKey;
 */
JNIEXPORT jobject JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1finalizeReg
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject);

/*
 * Class:     com_algomeet_signalingservice_jni_Opaque
 * Method:    c_storeRec
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_algomeet_signalingservice_jni_Opaque_c_1storeRec
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
