# ================================
# Spring Profile Configuration
# ================================
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ================================
# Local Profile Specific Settings
# ================================
---
spring:
  config:
    activate:
      on-profile: prod

  # ================================
  # MongoDB Configuration
  # ================================
  data:
    mongodb:
      uri: ${SPRING_DATASOURCE_URL_MONGODB}
      auto-index-creation: true


    # ================================
    # Redis Configuration
    # ================================
    redis:
      host: redis-svc
      port: 6379
      password: ${REDIS_PASSWORD}
      # TODO: Ensure Redis in production is:
      # - Password protected via requirepass
      # - Bound to internal IPs only (127.0.0.1 or private VPC)
      # - Configured with TLS if exposed
      # - Proper eviction policy and maxmemory set
      # - Persistence configured (AOF/RDB) as needed

  # ================================
  # JSON Formatting (Optional)
  # ================================
  jackson:
    serialization:
      INDENT_OUTPUT: true

  application:
    name: chat-service

group:
  service:
    url: http://group-service:8087
media:
  service:
    url: http://media-service:8095
jwt:
  secret: ${SPRING_JWT_SECRET}

# ================================
# Server Port
# ================================
server:
  port: ${SERVER_PORT:8084}
  # TODO: Move to .env for deployment-based overrides


logging:
  level:
    root: ${DEFAULT_LOG_LEVEL}
    com.algomeet.chatservice.controller: ${CHAT_LOG_LEVEL}
    com.algomeet.chatservice.service: ${CHAT_LOG_LEVEL}

mediaservice:
  support: false

