spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://192.168.0.156:5432/clorameet_db
    username: clorameet_sandro
    password: algo@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use 'validate' or 'none' in prod
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: mantu.amith@example.com
    password: 55Archuansh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8085

jwt:
  secret: Y0h4TkFxWkd6Um9TTktOVlFobU9naFN3SzY5cWhVY08=

meeting:
  expiration:
    minutes: 1440
      
feign:
  client:
    control-service:
      url: http://localhost:8090

