name: Build and Push to GHCR

on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ["auth-service", "chat-service", "contact-service", "meeting-service", "user-service", "notification-service"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # or 2, depending on your needs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: sonaialgoframe
          password: ${{ secrets.SONAI_PACKAGE_REGISTRY_TOKEN }}

      - name: Check if ${{ matrix.service }} has changes
        id: check_changes
        run: |
          CHANGED=$(git diff --name-only HEAD~1 HEAD | grep "^${{ matrix.service }}/" || true)
          if [ -n "$CHANGED" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create settings.xml
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          cat > ${{ github.workspace }}/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>sonaialgoframe</username>
                <password>${{ secrets.SONAI_PACKAGE_REGISTRY_TOKEN }}</password>
              </server>
              <server>
                <id>github-mtc</id>
                <username>sonaialgoframe</username>
                <password>${{ secrets.SONAI_PACKAGE_REGISTRY_TOKEN }}</password>
              </server>
              <server>
                <id>github-notify</id>
                <username>sonaialgoframe</username>
                <password>${{ secrets.SONAI_PACKAGE_REGISTRY_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build ${{ matrix.service }} with Maven
        if: steps.check_changes.outputs.changed == 'true'
        env:
          SPRING_PROFILES_ACTIVE: prod
        run: |
          cd ${{ matrix.service }}
          mvn clean package -DskipTests -s ${{ github.workspace }}/settings.xml

      - name: Build and push Docker image
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          IMAGE=ghcr.io/algoframe-private-limited/${{ matrix.service }}
          COMMIT_SHA=$(git rev-parse --short HEAD)

          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE:$COMMIT_SHA -t $IMAGE:latest ./${{ matrix.service }} --push

  trigger-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # needed to access HEAD~1

      - name: Determine which services changed
        id: detect
        run: |
            SERVICES=("auth-service" "chat-service" "contact-service" "meeting-service" "user-service")
            
            CHANGED_SERVICES=()
            
            for service in "${SERVICES[@]}"; do
              if git diff --name-only HEAD~1 HEAD | grep "^$service/" > /dev/null; then
                echo "$service changed"
                CHANGED_SERVICES+=("$service")
              fi
            done
            
            echo "changed_services=${CHANGED_SERVICES[*]}" >> $GITHUB_OUTPUT
            echo "Found changes in: ${CHANGED_SERVICES[*]}"

      - name: Trigger deployment in FAT(k8-deployment-config)
        if: steps.detect.outputs.changed_services != ''
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SONAI_PACKAGE_REGISTRY_TOKEN }}
          repository: Algoframe-Private-Limited/k8-deployment-config
          event-type: deploy-latest-image
