package com.algomeet.notificationservice.enums;

public enum NotificationType {
	USER_ONLINE,
	USER_OFFLINE,
	MESSAGE,
	AUDIO_CALL,
	VIDEO_CALL,
	AUDIO_MISCALL,
	VIDEO_MISCALL,
	FRIEND_REQUEST_RECEIVED,
	FRIEND_REQUEST_ACCEPTED,
	MEETING_INVITE_RECIEVED,
	MEETING_INVITE_ACCEPTED;	
}
